Blocked mlp single layer in bf16
plaidml/tpp-sandbox pull request #58
Opened 2022-10-12 08:26 UTC by KavithaTipturMadhu

2022-10-12 09:30 UTC, rengolin commented
The test failure is not related to the code here and is super weird. @hfp any ideas?

2022-10-12 09:31 UTC, rengolin commented
Otherwise, patch looks good. I'll let @chelini look at the IR shape to spot anything I missed.

2022-10-12 10:14 UTC, chelini requested changes

2022-10-12 10:14 UTC, chelini commented on test/BF16/mlp-single-layer-blocked-bf16.mlir
> +//RUN:standalone-opt %s -linalg-ext-to-loops -convert-linalg-to-loops -convert-tpp-to-xsmm -convert-xsmm-to-func -convert-vector-to-scf -convert-scf-to-cf -convert-vector-to-llvm -convert-func-to-llv
please add a space.

2022-10-12 10:14 UTC, chelini commented on test/BF16/mlp-single-layer-blocked-bf16.mlir
> +// RUN: mlir-cpu-runner \
Can you please check the test result?

2022-10-12 10:14 UTC, chelini commented on include/Standalone/Dialect/Tpp/TppOps.td
> +def TppBRGEMMPackedMemrefInput : StaticMemRefRankOf<[AnyFloat], [3,4]>;
Can you please add verifier checks for this change? Similar with what you did for gemm.

2022-10-12 10:14 UTC, chelini commented on include/Standalone/Dialect/Tpp/TppOps.td
> +def TppBRGEMMPackedMemrefInput : StaticMemRefRankOf<[AnyFloat], [3,4]>;
Also IREE direction for handling bf16 is maybe a good idea here. We are opening up this op too much. But let's discuss later and ignore this comment for now.

2022-10-13 09:29 UTC, chelini approved these changes

2022-10-13 09:33 UTC, merged